### ISSUE TITLE
BLEU implementation

### ISSUE THREAD

**Issue by forrestbao** [alaister123/Addon_EvalBase#1]
Thanks for the wrapper... questions and comments: 
1. Why using sacrebleu instead of BLEU?  https://huggingface.co/spaces/evaluate-metric/bleu
2. In HF's `evaluate` library, both Sacrebleu and BLEU takes a list of references and a list of summaries as inputs. So the for loop can be saved.  https://github.com/alaister123/Addon_EvalBase/blob/cf339ba1f944badcc5f18e7f7915021b615cba29/additional_metics.py#L28-L32
3. Instead of creating a class, a shorter way is to simply pass the bleu or sacrebleu function to EvalBase, like this https://github.com/SigmaWe/EvalBase/blob/964b9d8044f2d4410635f3b73f025f47dfdfceed/run_exp.py#L10-L13

**Comment by alaister123** [comment]
For Question 1:  `evaluate.load("bleu")` outputs error for me for some reason



---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-2fadec31e6ee> in <module>
----> 1 evaluate.load("bleu")

~\anaconda3\lib\site-packages\evaluate\loading.py in load(path, config_name, module_type, process_id, num_process, cache_dir, experiment_id, keep_in_memory, download_config, download_mode, revision, **init_kwargs)
    729     """
    730     download_mode = DownloadMode(download_mode or DownloadMode.REUSE_DATASET_IF_EXISTS)
--> 731     evaluation_module = evaluation_module_factory(
    732         path, module_type=module_type, revision=revision, download_config=download_config, download_mode=download_mode
    733     )

~\anaconda3\lib\site-packages\evaluate\loading.py in evaluation_module_factory(path, module_type, revision, download_config, download_mode, force_local_path, dynamic_modules_path, **download_kwargs)
    679             if not isinstance(e1, (ConnectionError, FileNotFoundError)):
    680                 raise e1 from None
--> 681             raise FileNotFoundError(
    682                 f"Couldn't find a module script at {relative_to_absolute_path(combined_path)}. "
    683                 f"Module '{path}' doesn't exist on the Hugging Face Hub either."

FileNotFoundError: Couldn't find a module script at C:\XXX\bleu\bleu.py. Module 'bleu' doesn't exist on the Hugging Face Hub either.

**Comment by alaister123** [comment]
For Q2&3: The HF code for bleu aggregates score, this cannot be turned off. Refer to this notebook.
https://github.com/alaister123/Weekly_Update/blob/main/04172023/Bleu%20Code%20Problem.ipynb

**Comment by forrestbao** [comment]
> For Q2&3: The HF code for bleu aggregates score, this cannot be turned off. Refer to this notebook. https://github.com/alaister123/Weekly_Update/blob/main/04172023/Bleu%20Code%20Problem.ipynb

Ah, my mistake. I didn't realize that HF's BLEU and SacreBLEU returns only aggregated scores on all summaries. Yeah, you are right, in that case, you'd have to use a for-loop.

**Comment by forrestbao** [comment]
Maybe HF's server had an issue when you were downloading. I just tried. No problem. Try again? 

> For Question 1: `evaluate.load("bleu")` outputs error for me for some reason
> 
> FileNotFoundError Traceback (most recent call last) in ----> 1 evaluate.load("bleu")
> 
> ~\anaconda3\lib\site-packages\evaluate\loading.py in load(path, config_name, module_type, process_id, num_process, cache_dir, experiment_id, keep_in_memory, download_config, download_mode, revision, **init_kwargs) 729 """ 730 download_mode = DownloadMode(download_mode or DownloadMode.REUSE_DATASET_IF_EXISTS) --> 731 evaluation_module = evaluation_module_factory( 732 path, module_type=module_type, revision=revision, download_config=download_config, download_mode=download_mode 733 )
> 
> ~\anaconda3\lib\site-packages\evaluate\loading.py in evaluation_module_factory(path, module_type, revision, download_config, download_mode, force_local_path, dynamic_modules_path, **download_kwargs) 679 if not isinstance(e1, (ConnectionError, FileNotFoundError)): 680 raise e1 from None --> 681 raise FileNotFoundError( 682 f"Couldn't find a module script at {relative_to_absolute_path(combined_path)}. " 683 f"Module '{path}' doesn't exist on the Hugging Face Hub either."
> 
> FileNotFoundError: Couldn't find a module script at C:\Users\alaister\Desktop\EvalBase_refactor\bleu\bleu.py. Module 'bleu' doesn't exist on the Hugging Face Hub either.

**Comment by alaister123** [comment]
> Maybe HF's server had an issue when you were downloading. I just tried. No problem. Try again?
> 
> > For Question 1: `evaluate.load("bleu")` outputs error for me for some reason
> > FileNotFoundError Traceback (most recent call last) in ----> 1 evaluate.load("bleu")
> > ~\anaconda3\lib\site-packages\evaluate\loading.py in load(path, config_name, module_type, process_id, num_process, cache_dir, experiment_id, keep_in_memory, download_config, download_mode, revision, **init_kwargs) 729 """ 730 download_mode = DownloadMode(download_mode or DownloadMode.REUSE_DATASET_IF_EXISTS) --> 731 evaluation_module = evaluation_module_factory( 732 path, module_type=module_type, revision=revision, download_config=download_config, download_mode=download_mode 733 )
> > ~\anaconda3\lib\site-packages\evaluate\loading.py in evaluation_module_factory(path, module_type, revision, download_config, download_mode, force_local_path, dynamic_modules_path, **download_kwargs) 679 if not isinstance(e1, (ConnectionError, FileNotFoundError)): 680 raise e1 from None --> 681 raise FileNotFoundError( 682 f"Couldn't find a module script at {relative_to_absolute_path(combined_path)}. " 683 f"Module '{path}' doesn't exist on the Hugging Face Hub either."
> > FileNotFoundError: Couldn't find a module script at C:\Users\alaister\Desktop\EvalBase_refactor\bleu\bleu.py. Module 'bleu' doesn't exist on the Hugging Face Hub either.

Yeah, this is my internet's problem. There's also people with the same problem https://huggingface.co/spaces/evaluate-metric/bleu/discussions/6 

I added bleu function and kept sacrebleu function just incase people got internet issues.
