### ISSUE TITLE
METEOR score 

### ISSUE THREAD

**Issue by forrestbao** [alaister123/Addon_EvalBase#2]
Your comment shows that you have found the HF's `evaluate` library. But the code shows that the METEOR score implementation is from NLTK. Why? I prefer HF's implementation as we can easily integrate it with EvalBase. 

https://github.com/alaister123/Addon_EvalBase/blob/cf339ba1f944badcc5f18e7f7915021b615cba29/additional_metics.py#L6-L17

**Comment by alaister123** [comment]
Okay will fix
